### ISSUE TITLE
突然找不到aar了，之前都好好的

### ISSUE THREAD

**Issue by colorbeach** [CarGuo/FrescoUtils#13]
上个月还能编译的，今天突然这样了：
> Could not find FrescoUtils-v1.2.1.aar (com.github.CarGuo:FrescoUtils:v1.2.1).
     Searched in the following locations:
         https://jitpack.io/com/github/CarGuo/FrescoUtils/v1.2.1/FrescoUtils-v1.2.1.aar

这是什么情况呀，打开aar链接就提示not found

**Comment by CarGuo** [comment]
https://jitpack.io/com/github/CarGuo/FrescoUtils/master-9cc374e03e-1/build.log 看了下，项目太老了，现在 jitpack 上不支持了，建议本地依赖吧～

**Comment by colorbeach** [comment]
1.2.0版本还是能找到的

> https://jitpack.io/com/github/CarGuo/FrescoUtils/master-9cc374e03e-1/build.log 看了下，项目太老了，现在 jitpack 上不支持了，建议本地依赖吧～

谢谢
