### ISSUE TITLE
FrescoUtils-v1.2.1.aar在线引用不到了，求大佬解答？

### ISSUE THREAD

**Issue by xsdxqn** [CarGuo/FrescoUtils#14]
Could not find FrescoUtils-v1.2.1.aar (com.github.CarGuo:FrescoUtils:v1.2.1).
     Searched in the following locations:
         https://jitpack.io/com/github/CarGuo/FrescoUtils/v1.2.1/FrescoUtils-v1.2.1.aar

**Comment by CarGuo** [comment]
用  implementation "com.github.CarGuo:FrescoUtils:c39608c9b2"
