### ISSUE TITLE
请教个问题，这个最低版本能支持到多少？

### ISSUE THREAD

**Issue by wangguifa** [CarGuo/FrescoUtils#3]
我想问下sdk最低版本支持多少呢

**Comment by CarGuo** [comment]
不好意思，之前一直没注意，最新版本1.0.2现在我调到了API 15

**Comment by wangguifa** [comment]
好的，谢谢

**Comment by wangguifa** [comment]
compile 'com.shuyu:FrescoUtils:1.0.1'这个是上一个版本吗？
现在换成这个compile 'com.github.CarGuo:FrescoUtils:v1.0.2'出错了

Error: Failed to resolve: com.github.CarGuo:FrescoUtils:v1.0.2
Show in File
Show in Project Structure dialog


是我的错吗？

**Comment by CarGuo** [comment]
具体看这个  https://github.com/CarGuo/FrescoUtils/issues/2   因为某些原因，现在切换到了仓库，还请见谅

**Comment by wangguifa** [comment]
可是现在导入错误,这是什么原因呢？新建一个项目导入也是出错，可是上一个版本就没问题？能指导一下吗？谢谢

**Comment by CarGuo** [comment]
因为之前是jcenter的，1.0.2开始都是在jitpack上面了，所以需要maven { url 'https://jitpack.io' }，在主页的readme上面有写着哟！还请见谅哈~
```
allprojects {
    repositories {
        ...
        maven { url 'https://jitpack.io' }
    }
}
dependencies {
    compile 'com.github.CarGuo:FrescoUtils:v1.0.2'
}
```

**Comment by wangguifa** [comment]
好的，谢谢哈，其实我是菜鸟，不懂maven，麻烦你了

**Comment by wangguifa** [comment]
现在可以用了，麻烦你了
